/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectofinal;

import java.awt.Color;
import java.awt.*;
import java.util.ArrayList;
import javax.swing.*;
import javax.swing.OverlayLayout;
import Clases.Persona;
import java.text.SimpleDateFormat;
import java.util.Date;
import Clases.DbCon;
import com.amazonaws.client.builder.AwsClientBuilder;
import com.amazonaws.services.dynamodbv2.AmazonDynamoDB;
import com.amazonaws.services.dynamodbv2.AmazonDynamoDBClientBuilder;
import com.amazonaws.services.dynamodbv2.document.DynamoDB;
import com.amazonaws.services.dynamodbv2.document.Item;
import javax.swing.JOptionPane;
import java.io.*;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.util.ArrayList;
import java.util.List;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import javax.swing.table.DefaultTableModel;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.math.BigDecimal;
import java.util.Arrays;
import java.sql.SQLException;
import java.sql.ResultSet;
import java.util.HashSet;
import java.util.Set;
import java.util.logging.Level;
import java.util.logging.Logger;
import com.amazonaws.client.builder.AwsClientBuilder;
import com.amazonaws.services.dynamodbv2.AmazonDynamoDB;
import com.amazonaws.services.dynamodbv2.AmazonDynamoDBClientBuilder;
import com.amazonaws.services.dynamodbv2.document.DynamoDB;
import com.amazonaws.services.dynamodbv2.document.Item;
import com.amazonaws.services.dynamodbv2.document.ItemCollection;
import com.amazonaws.services.dynamodbv2.document.ScanOutcome;
import com.amazonaws.services.dynamodbv2.document.Table;
import com.amazonaws.services.dynamodbv2.document.internal.IteratorSupport;
import com.amazonaws.services.dynamodbv2.model.AttributeDefinition;
import com.amazonaws.services.dynamodbv2.model.CreateTableRequest;

import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import org.json.JSONArray;
import org.json.JSONObject;
import proyectofinal.NewJFrame;
import static proyectofinal.NewJFrame.Uactual;

public class UsserDis extends javax.swing.JFrame {

    AmazonDynamoDB cliente = AmazonDynamoDBClientBuilder.standard()
            .withEndpointConfiguration(new AwsClientBuilder.EndpointConfiguration("http://localhost:8000", "local"))
            .build();
    DynamoDB dynamoDB = new DynamoDB(cliente);

    public UsserDis() {

        initComponents();
        iniciarVA();
        //Nombre_Usuario_Label.setText("Bienvenido " + NewJFrame.Uactual.getNombre());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CrearMatriculas = new javax.swing.JDialog();
        jPanel13 = new javax.swing.JPanel();
        NombreLista12 = new javax.swing.JLabel();
        HEADERCOSO14 = new javax.swing.JLabel();
        Agregarintegrante6 = new javax.swing.JButton();
        jScrollPane8 = new javax.swing.JScrollPane();
        CrearTablaMatriculas = new javax.swing.JTable();
        PanelAdministrador = new javax.swing.JPanel();
        Panel_Lateral = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        CrearUsuario_AdminTools_MW = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        ListarUsuarios_AdminTools_MW = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        botonuniversal = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        Crud_Usuarios_AP = new javax.swing.JPanel();
        ListarPane_AdminTools_MW = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TablaListar = new javax.swing.JTable();
        CB_Listar = new javax.swing.JComboBox<>();
        CrearPane_AdminTools_MW1 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        CB_Crear = new javax.swing.JComboBox<>();

        CrearMatriculas.setMinimumSize(new java.awt.Dimension(720, 520));

        jPanel13.setBackground(new java.awt.Color(247, 246, 220));
        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        NombreLista12.setBackground(new java.awt.Color(247, 246, 220));
        NombreLista12.setFont(new java.awt.Font("Roboto Medium", 1, 18)); // NOI18N
        NombreLista12.setForeground(new java.awt.Color(78, 148, 79));
        jPanel13.add(NombreLista12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        HEADERCOSO14.setFont(new java.awt.Font("Roboto Medium", 1, 30)); // NOI18N
        HEADERCOSO14.setForeground(new java.awt.Color(78, 148, 79));
        HEADERCOSO14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        HEADERCOSO14.setText("Crear Matriculas");
        HEADERCOSO14.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        HEADERCOSO14.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel13.add(HEADERCOSO14, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 320, 40));

        Agregarintegrante6.setBackground(new java.awt.Color(78, 148, 79));
        Agregarintegrante6.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        Agregarintegrante6.setForeground(new java.awt.Color(233, 239, 192));
        Agregarintegrante6.setText("            Crear");
        Agregarintegrante6.setBorder(null);
        Agregarintegrante6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Agregarintegrante6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Agregarintegrante6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Agregarintegrante6ActionPerformed(evt);
            }
        });
        jPanel13.add(Agregarintegrante6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, 120, 40));

        CrearTablaMatriculas.setBackground(new java.awt.Color(233, 239, 192));
        CrearTablaMatriculas.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        CrearTablaMatriculas.setForeground(new java.awt.Color(78, 148, 79));
        CrearTablaMatriculas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null}
            },
            new String [] {
                "# Matricula", "dni_alumno", "tipo_lic", "fecha_matricula"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                true, false, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        CrearTablaMatriculas.setToolTipText("");
        CrearTablaMatriculas.setGridColor(new java.awt.Color(131, 189, 117));
        CrearTablaMatriculas.setSelectionBackground(new java.awt.Color(78, 148, 79));
        jScrollPane8.setViewportView(CrearTablaMatriculas);

        jPanel13.add(jScrollPane8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 650, 50));

        javax.swing.GroupLayout CrearMatriculasLayout = new javax.swing.GroupLayout(CrearMatriculas.getContentPane());
        CrearMatriculas.getContentPane().setLayout(CrearMatriculasLayout);
        CrearMatriculasLayout.setHorizontalGroup(
            CrearMatriculasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CrearMatriculasLayout.createSequentialGroup()
                .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, 715, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 12, Short.MAX_VALUE))
        );
        CrearMatriculasLayout.setVerticalGroup(
            CrearMatriculasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CrearMatriculasLayout.createSequentialGroup()
                .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, 555, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 12, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(250, 50));
        setResizable(false);

        PanelAdministrador.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Panel_Lateral.setBackground(new java.awt.Color(233, 239, 192));
        Panel_Lateral.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(180, 225, 151));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(78, 148, 79));
        jLabel1.setText("Herrramientas ");
        jPanel4.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));

        jSeparator1.setBackground(new java.awt.Color(78, 148, 79));
        jSeparator1.setForeground(new java.awt.Color(78, 148, 79));
        jSeparator1.setPreferredSize(new java.awt.Dimension(50, 30));
        jPanel4.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 211, 10));

        CrearUsuario_AdminTools_MW.setBackground(new java.awt.Color(78, 148, 79));
        CrearUsuario_AdminTools_MW.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        CrearUsuario_AdminTools_MW.setForeground(new java.awt.Color(233, 239, 192));
        CrearUsuario_AdminTools_MW.setText("Crear ");
        CrearUsuario_AdminTools_MW.setBorder(null);
        CrearUsuario_AdminTools_MW.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CrearUsuario_AdminTools_MW.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        CrearUsuario_AdminTools_MW.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CrearUsuario_AdminTools_MWActionPerformed(evt);
            }
        });
        jPanel4.add(CrearUsuario_AdminTools_MW, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 190, 31));

        jPanel5.setBackground(new java.awt.Color(78, 148, 79));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 31, Short.MAX_VALUE)
        );

        jPanel4.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 100, 31));

        ListarUsuarios_AdminTools_MW.setBackground(new java.awt.Color(78, 148, 79));
        ListarUsuarios_AdminTools_MW.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        ListarUsuarios_AdminTools_MW.setForeground(new java.awt.Color(233, 239, 192));
        ListarUsuarios_AdminTools_MW.setText("Listar ");
        ListarUsuarios_AdminTools_MW.setBorder(null);
        ListarUsuarios_AdminTools_MW.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ListarUsuarios_AdminTools_MW.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        ListarUsuarios_AdminTools_MW.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListarUsuarios_AdminTools_MWActionPerformed(evt);
            }
        });
        jPanel4.add(ListarUsuarios_AdminTools_MW, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 190, 31));

        jPanel8.setBackground(new java.awt.Color(78, 148, 79));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 31, Short.MAX_VALUE)
        );

        jPanel4.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 100, 31));

        botonuniversal.setBackground(new java.awt.Color(78, 148, 79));
        botonuniversal.setFont(new java.awt.Font("Roboto Medium", 1, 24)); // NOI18N
        botonuniversal.setForeground(new java.awt.Color(233, 239, 192));
        botonuniversal.setText("AutoEscuela");
        botonuniversal.setBorder(null);
        botonuniversal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonuniversalActionPerformed(evt);
            }
        });
        jPanel4.add(botonuniversal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 230, 60));

        jSeparator3.setBackground(new java.awt.Color(78, 148, 79));
        jSeparator3.setForeground(new java.awt.Color(78, 148, 79));
        jSeparator3.setPreferredSize(new java.awt.Dimension(50, 30));
        jPanel4.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 211, 10));

        Panel_Lateral.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 620));

        Crud_Usuarios_AP.setLayout(new javax.swing.OverlayLayout(Crud_Usuarios_AP));

        ListarPane_AdminTools_MW.setBackground(new java.awt.Color(247, 246, 220));
        ListarPane_AdminTools_MW.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel20.setFont(new java.awt.Font("Roboto Medium", 1, 24)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(78, 148, 79));
        jLabel20.setText("L i s t a r ");
        ListarPane_AdminTools_MW.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        TablaListar.setBackground(new java.awt.Color(233, 239, 192));
        TablaListar.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        TablaListar.setForeground(new java.awt.Color(78, 148, 79));
        TablaListar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Usuario", "Id"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TablaListar.setGridColor(new java.awt.Color(131, 189, 117));
        TablaListar.setSelectionBackground(new java.awt.Color(78, 148, 79));
        jScrollPane2.setViewportView(TablaListar);

        ListarPane_AdminTools_MW.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 734, 420));

        CB_Listar.setBackground(new java.awt.Color(180, 225, 151));
        CB_Listar.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        CB_Listar.setForeground(new java.awt.Color(78, 148, 79));
        CB_Listar.setBorder(null);
        CB_Listar.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                CB_ListarItemStateChanged(evt);
            }
        });
        CB_Listar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CB_ListarActionPerformed(evt);
            }
        });
        ListarPane_AdminTools_MW.add(CB_Listar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 350, 30));

        Crud_Usuarios_AP.add(ListarPane_AdminTools_MW);

        CrearPane_AdminTools_MW1.setBackground(new java.awt.Color(247, 246, 220));
        CrearPane_AdminTools_MW1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Roboto Medium", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(78, 148, 79));
        jLabel10.setText("C r e a r  ");
        CrearPane_AdminTools_MW1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 23, -1, -1));

        jButton4.setBackground(new java.awt.Color(180, 225, 151));
        jButton4.setFont(new java.awt.Font("Roboto Medium", 1, 18)); // NOI18N
        jButton4.setForeground(new java.awt.Color(78, 148, 79));
        jButton4.setText("C r e a r  N u e v o");
        jButton4.setBorder(null);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        CrearPane_AdminTools_MW1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 380, 220, 150));

        CB_Crear.setBackground(new java.awt.Color(180, 225, 151));
        CB_Crear.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        CB_Crear.setForeground(new java.awt.Color(78, 148, 79));
        CB_Crear.setBorder(null);
        CB_Crear.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                CB_CrearItemStateChanged(evt);
            }
        });
        CB_Crear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CB_CrearActionPerformed(evt);
            }
        });
        CrearPane_AdminTools_MW1.add(CB_Crear, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 220, 30));

        Crud_Usuarios_AP.add(CrearPane_AdminTools_MW1);

        Panel_Lateral.add(Crud_Usuarios_AP, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, 790, 580));

        PanelAdministrador.add(Panel_Lateral, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1080, 620));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelAdministrador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelAdministrador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CrearUsuario_AdminTools_MWActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CrearUsuario_AdminTools_MWActionPerformed
        modelocomboboxCREATE();
        CrearPane_AdminTools_MW1.setVisible(true);
        Crud_Usuarios_AP.setVisible(true);
        ListarPane_AdminTools_MW.setVisible((false));


    }//GEN-LAST:event_CrearUsuario_AdminTools_MWActionPerformed

    private void ListarUsuarios_AdminTools_MWActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListarUsuarios_AdminTools_MWActionPerformed
        jLabel20.setText("L i s t a r");
        //CB_ID.setVisible((false));
        modelocomboboxListar();

        CrearPane_AdminTools_MW1.setVisible(false);
        ListarPane_AdminTools_MW.setVisible((true));
        Crud_Usuarios_AP.setVisible(true);

        modeloTABLEListar();


            }//GEN-LAST:event_ListarUsuarios_AdminTools_MWActionPerformed

    private void botonuniversalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonuniversalActionPerformed
        TodoVfalse();
    }//GEN-LAST:event_botonuniversalActionPerformed

    private void CB_ListarItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_CB_ListarItemStateChanged
        modeloTABLEListar();

    }//GEN-LAST:event_CB_ListarItemStateChanged

    private void CB_ListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CB_ListarActionPerformed
        modeloTABLEListar();
    }//GEN-LAST:event_CB_ListarActionPerformed

    private void CB_CrearItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_CB_CrearItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_CB_CrearItemStateChanged

    private void CB_CrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CB_CrearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CB_CrearActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {
        String entidad = (String) CB_Crear.getSelectedItem();
        switch (entidad) {
            case "Matriculas": {
                Table tabla = dynamoDB.getTable("Matriculas");
                if (tabla.getItem("dni_alumno", Uactual.getID()) == null) {
                    ArrayList<String> NombresColumnas = new ArrayList<String>();
                    NombresColumnas.add("n_matricula");
                    NombresColumnas.add("dni_alumno");
                    NombresColumnas.add("tipo_lic");
                    NombresColumnas.add("fecha_matricula");
                    DefaultTableModel tableModel = new DefaultTableModel(NombresColumnas.toArray(), 0);
                    Object[] row = new Object[]{"", Uactual.getID(), "", ""};
                    tableModel.addRow(row);

                    CrearTablaMatriculas.setModel(tableModel);
                    CrearMatriculas.setVisible(true);
                } else {
                    JOptionPane.showMessageDialog(rootPane, "Solo 1 matricula por alumno, intentelo mas tarde");
                }
            }
            break;
            case "Examenes": {
                Table tabla = dynamoDB.getTable("Examenes");
                Table tabla2 = dynamoDB.getTable("Matriculas");

                Item it = tabla2.getItem("dni_alumno", Uactual.getID());
                Item Br = tabla.getItem("matricula", it.get("n_matricula"));

                if (Br == null) {
                    int nota = 0;

                    // Pregunta 1
                    String respuesta1 = JOptionPane.showInputDialog(null, "¿Se puede pasar un semáforo en rojo?");
                    if (respuesta1 != null && respuesta1.equalsIgnoreCase("No")) {
                        nota++;
                    }

                    // Pregunta 2
                    Object[] opciones = {"Verdadero", "Falso"};
                    int respuesta2 = JOptionPane.showOptionDialog(null,
                            "¿Se puede usar el teléfono al conducir?", "Pregunta",
                            JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null,
                            opciones, opciones[0]);
                    if (respuesta2 == JOptionPane.YES_OPTION) {
                        nota++;
                    }

                    // Crear un nuevo ítem actualizado con la nota
                    Item itemActualizado = new Item()
                            .withPrimaryKey("fecha_examen", Br.getString("fecha_examen"))
                            .withString("tipo_examen", Br.getString("tipo_examen"))
                            .withString("matricula", Br.getString("matricula"))
                            .withInt("n_examen", Br.getInt("n_examen"))
                            .withString("informe", Br.getString("informe"))
                            .withBoolean("resultado", nota >= 1); // Actualizar el resultado basado en la nota

                    // Borrar el ítem existente
                    tabla.deleteItem("matricula", it.get("n_matricula"));

                    // Insertar el nuevo ítem actualizado
                    tabla.putItem(itemActualizado);

                    // Mostrar la nota final
                    JOptionPane.showMessageDialog(null, "Tu nota es: " + nota + "/2");

                } else {
                    JOptionPane.showMessageDialog(rootPane, "Solo 1 Examen por alumno, inténtelo más tarde");
                }

            }
            break;
            default:
                // Si el valor del String no coincide con ninguna de las opciones anteriores
                break;
        }

    }


    private void Agregarintegrante6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Agregarintegrante6ActionPerformed
//crear matriclas

        ArrayList<Object> atributos = new ArrayList<>();
        DefaultTableModel tableModel = (DefaultTableModel) CrearTablaMatriculas.getModel();
        for (int i = 0; i < tableModel.getColumnCount(); i++) {
            Object valorCelda = tableModel.getValueAt(0, i);
            atributos.add((valorCelda != null) ? valorCelda.toString() : "null");
        }

        for (int i = 0; i < tableModel.getColumnCount(); i++) {
            tableModel.setValueAt("", 0, i);
        }

        CrearTablaMatriculas.setModel(tableModel);

        Item item = new Item()
                .withPrimaryKey("n_matricula", atributos.get(0).toString())
                .withString("dni_alumno", atributos.get(1).toString())
                .withString("tipo_lic", atributos.get(2).toString())
                .withString("fecha_matricula", atributos.get(3).toString());

        com.mycompany.proyecto.Proyecto.crearItem("Matriculas", item);
    }//GEN-LAST:event_Agregarintegrante6ActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UsserDis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UsserDis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UsserDis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UsserDis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UsserDis().setVisible(true);
            }
        });
    }

    public void iniciarVA() {
        Crud_Usuarios_AP.setVisible(false);
        CrearPane_AdminTools_MW1.setVisible(false);
    }

    public void TodoVfalse() {
        Crud_Usuarios_AP.setVisible(false);
        CrearPane_AdminTools_MW1.setVisible(false);
        ListarPane_AdminTools_MW.setVisible(false);

    }

    //TODO DE LISTAR
    public void modelocomboboxListar() {
        CB_Listar.getModel();
        DefaultComboBoxModel m = new DefaultComboBoxModel();
        for (String entidade : entidades) {
            m.addElement(entidade);
        }
        CB_Listar.setModel(m);
    }

    public void modeloTABLEListar() {
        String entidad = (String) CB_Listar.getSelectedItem();
        DefaultTableModel m = new DefaultTableModel();
        m = (TraerTabla(entidad));
        TablaListar.setModel(m);
    }

    //TODO ELIMINAR
//TODO DE CREAR
    public void modelocomboboxCREATE() {
        CB_Crear.getModel();
        DefaultComboBoxModel m = new DefaultComboBoxModel();
        for (String entidade : entidadesCrear) {
            m.addElement(entidade);
        }
        CB_Crear.setModel(m);
    }

    public static ArrayList<Persona> ListUssers = new ArrayList();

    public static ArrayList<String> entidades = new ArrayList<String>() {
        {
            add("Matriculas");
            add("Examenes");

        }
    };

    public static ArrayList<String> entidadesModif = new ArrayList<String>() {
        {
            add("Matriculas");
            add("Examenes");
        }
    };

    public static ArrayList<String> entidadesCrear = new ArrayList<String>() {
        {
            add("Matriculas");
            add("Examenes");
        }
    };

    public DefaultTableModel TraerTabla(String nombreTabla) {
        Table table = dynamoDB.getTable(nombreTabla);
        ArrayList<String> Atributos = new ArrayList<String>();
        switch (nombreTabla) {

            case "Matriculas": {
                ArrayList<String> NombresColumnas = new ArrayList<String>();
                NombresColumnas.add("n_matricula");
                NombresColumnas.add("dni_alumno");
                NombresColumnas.add("tipo_lic");
                NombresColumnas.add("fecha_matricula");

                DefaultTableModel tableModel = new DefaultTableModel(NombresColumnas.toArray(), 0);
                ItemCollection<ScanOutcome> items = table.scan();
                Iterator<Item> iter = items.iterator();
                while (iter.hasNext()) {
                    Item item = iter.next();
                    Object[] row = new Object[]{item.get("n_matricula"), item.get("dni_alumno"), item.get("tipo_lic"), item.get("fecha_matricula")};
                    tableModel.addRow(row);
                }
                return tableModel;
            }

            case "Examenes": {
                //continuar con los eamenes
                ArrayList<String> NombresColumnas = new ArrayList<String>();
                NombresColumnas.add("fecha_examen");
                NombresColumnas.add("tipo_examen");
                NombresColumnas.add("matricula");
                NombresColumnas.add("n_examen");
                NombresColumnas.add("informe");
                NombresColumnas.add("resultado");

                DefaultTableModel tableModel = new DefaultTableModel(NombresColumnas.toArray(), 0);
                ItemCollection<ScanOutcome> items = table.scan();
                Iterator<Item> iter = items.iterator();
                while (iter.hasNext()) {
                    Item item = iter.next();
                    Object[] row = new Object[]{item.get("fecha_examen"), item.get("tipo_examen"), item.get("matricula"), item.get("n_examen"), item.get("informe"), item.get("resultado")};
                    tableModel.addRow(row);
                }
                return tableModel;
            }

        }
        return null;
    }

    public static void guardarEnArchivo() {
        try (ObjectOutputStream oos = new ObjectOutputStream(new FileOutputStream("./personas.bin"))) {
            oos.writeObject(ListUssers);
        } catch (IOException e) {
            e.printStackTrace();
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Agregarintegrante6;
    private javax.swing.JComboBox<String> CB_Crear;
    private javax.swing.JComboBox<String> CB_Listar;
    private javax.swing.JDialog CrearMatriculas;
    private javax.swing.JPanel CrearPane_AdminTools_MW1;
    private javax.swing.JTable CrearTablaMatriculas;
    private javax.swing.JButton CrearUsuario_AdminTools_MW;
    private javax.swing.JPanel Crud_Usuarios_AP;
    private javax.swing.JLabel HEADERCOSO14;
    private javax.swing.JPanel ListarPane_AdminTools_MW;
    private javax.swing.JButton ListarUsuarios_AdminTools_MW;
    private javax.swing.JLabel NombreLista12;
    private javax.swing.JPanel PanelAdministrador;
    private javax.swing.JPanel Panel_Lateral;
    private javax.swing.JTable TablaListar;
    private javax.swing.JButton botonuniversal;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    // End of variables declaration//GEN-END:variables
}
